{% set name = "wagtail-treemodeladmin" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e68a874844f54fbd774285a1d8b205c375efc0e9b72c3193aa7b6c527f09d852

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=5.1
    - wagtail-modeladmin >=1.0

test:
  imports:
    - treemodeladmin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: TreeModelAdmin for Wagtail
  home: https://github.com/cfpb/wagtail-treemodeladmin
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
