{% set name = "wagtail-treemodeladmin" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f4d83463cf0cff23354c315c70e8c84b6021aa79cc762e5a403f1f2b3c25240c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - wagtail >=5.1
    - wagtail-modeladmin >=1.0

test:
  imports:
    - treemodeladmin
  commands:
    - pip check
  requires:
    - pip

about:
  summary: TreeModelAdmin for Wagtail
  home: https://github.com/cfpb/wagtail-treemodeladmin
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
